apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kubeinvaders
  namespace: kubeinvaders
  annotations:
    kubernetes.io/ingress.class: addon-http-application-routing
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - kubeinvaders.<DNS ZONE NAME>
  rules:
    - host: kubeinvaders.<DNS ZONE NAME>
      http:
        paths:
          - path: /
            backend:
              serviceName: kubeinvaders
              servicePort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: kubeinvaders
  namespace: kubeinvaders
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    run: kubeinvaders
