kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeinvaders-rolebinding
  namespace: invaders
subjects:
  - kind: ServiceAccount
    name: kubeinvaders
    namespace: invaders
roleRef:
  kind: Role
  name: kubeinvaders-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeinvaders
  namespace: invaders
