name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1 
      - name: Setup .NET Core 2.2.207
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.207
      - name: Setup .NET Core 3.1.101
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Setup side by side .NET SDKs
        run: |
          rsync -a ${DOTNET_ROOT/3.1.101/2.2.207}/* $DOTNET_ROOT/
      - name: Build with dotnet
        run: find . -type f \( -iname "*.csproj" \) | xargs -n1 dotnet build
