name: .NET Core

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build with dotnet
        run: find . -type f \( -iname "*.csproj" \) | xargs -n1 dotnet build
